# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python_cheat_sheet_gui.ui'
#
# Created: Thu Jul  4 16:46:53 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PythonCheatSheet(object):
    def setupUi(self, PythonCheatSheet):
        PythonCheatSheet.setObjectName(_fromUtf8("PythonCheatSheet"))
        PythonCheatSheet.setWindowModality(QtCore.Qt.ApplicationModal)
        PythonCheatSheet.resize(560, 551)
        self.widget = QtGui.QWidget(PythonCheatSheet)
        self.widget.setGeometry(QtCore.QRect(12, 0, 516, 546))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.BasicsGroupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BasicsGroupBox.sizePolicy().hasHeightForWidth())
        self.BasicsGroupBox.setSizePolicy(sizePolicy)
        self.BasicsGroupBox.setObjectName(_fromUtf8("BasicsGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.BasicsGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.conditionals_button = QtGui.QPushButton(self.BasicsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.conditionals_button.setFont(font)
        self.conditionals_button.setAutoDefault(False)
        self.conditionals_button.setObjectName(_fromUtf8("conditionals_button"))
        self.gridLayout.addWidget(self.conditionals_button, 5, 0, 1, 1)
        self.strings_button = QtGui.QPushButton(self.BasicsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.strings_button.setFont(font)
        self.strings_button.setAutoDefault(False)
        self.strings_button.setObjectName(_fromUtf8("strings_button"))
        self.gridLayout.addWidget(self.strings_button, 2, 0, 1, 1)
        self.expressions_button = QtGui.QPushButton(self.BasicsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.expressions_button.setFont(font)
        self.expressions_button.setAutoDefault(False)
        self.expressions_button.setObjectName(_fromUtf8("expressions_button"))
        self.gridLayout.addWidget(self.expressions_button, 4, 0, 1, 1)
        self.lists_button = QtGui.QPushButton(self.BasicsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lists_button.setFont(font)
        self.lists_button.setAutoDefault(False)
        self.lists_button.setObjectName(_fromUtf8("lists_button"))
        self.gridLayout.addWidget(self.lists_button, 1, 0, 1, 1)
        self.keywords_button = QtGui.QPushButton(self.BasicsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.keywords_button.setFont(font)
        self.keywords_button.setAutoDefault(False)
        self.keywords_button.setObjectName(_fromUtf8("keywords_button"))
        self.gridLayout.addWidget(self.keywords_button, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.BasicsGroupBox, 0, 0, 2, 1)
        self.Important = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Important.sizePolicy().hasHeightForWidth())
        self.Important.setSizePolicy(sizePolicy)
        self.Important.setObjectName(_fromUtf8("Important"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Important)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.decorators_button = QtGui.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.decorators_button.setFont(font)
        self.decorators_button.setAutoDefault(False)
        self.decorators_button.setObjectName(_fromUtf8("decorators_button"))
        self.gridLayout_2.addWidget(self.decorators_button, 0, 0, 1, 1)
        self.examples_button = QtGui.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.examples_button.setFont(font)
        self.examples_button.setAutoDefault(False)
        self.examples_button.setObjectName(_fromUtf8("examples_button"))
        self.gridLayout_2.addWidget(self.examples_button, 4, 0, 1, 1)
        self.yield_button = QtGui.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yield_button.setFont(font)
        self.yield_button.setAutoDefault(False)
        self.yield_button.setObjectName(_fromUtf8("yield_button"))
        self.gridLayout_2.addWidget(self.yield_button, 2, 0, 1, 1)
        self.exceptions_button = QtGui.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exceptions_button.setFont(font)
        self.exceptions_button.setAutoDefault(False)
        self.exceptions_button.setObjectName(_fromUtf8("exceptions_button"))
        self.gridLayout_2.addWidget(self.exceptions_button, 1, 0, 1, 1)
        self.twisted_button = QtGui.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.twisted_button.setFont(font)
        self.twisted_button.setAutoDefault(False)
        self.twisted_button.setObjectName(_fromUtf8("twisted_button"))
        self.gridLayout_2.addWidget(self.twisted_button, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.Important, 0, 1, 2, 1)
        spacerItem = QtGui.QSpacerItem(20, 208, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(199, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.search_label = QtGui.QLabel(self.widget)
        self.search_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_label.setObjectName(_fromUtf8("search_label"))
        self.gridLayout_3.addWidget(self.search_label, 2, 0, 1, 1)
        self.search_text = QtGui.QLineEdit(self.widget)
        self.search_text.setObjectName(_fromUtf8("search_text"))
        self.gridLayout_3.addWidget(self.search_text, 2, 1, 1, 1)
        self.results_browser = QtGui.QTextBrowser(self.widget)
        self.results_browser.setObjectName(_fromUtf8("results_browser"))
        self.gridLayout_3.addWidget(self.results_browser, 3, 0, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(186, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.clear_button = QtGui.QPushButton(self.widget)
        self.clear_button.setAutoDefault(False)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.horizontalLayout.addWidget(self.clear_button)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 2)

        self.retranslateUi(PythonCheatSheet)
        QtCore.QMetaObject.connectSlotsByName(PythonCheatSheet)

    def retranslateUi(self, PythonCheatSheet):
        PythonCheatSheet.setWindowTitle(QtGui.QApplication.translate("PythonCheatSheet", "Python Cheat Sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.BasicsGroupBox.setTitle(QtGui.QApplication.translate("PythonCheatSheet", "Basics", None, QtGui.QApplication.UnicodeUTF8))
        self.conditionals_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Conditionals", None, QtGui.QApplication.UnicodeUTF8))
        self.strings_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Strings", None, QtGui.QApplication.UnicodeUTF8))
        self.expressions_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Expressions", None, QtGui.QApplication.UnicodeUTF8))
        self.lists_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Lists", None, QtGui.QApplication.UnicodeUTF8))
        self.keywords_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.Important.setTitle(QtGui.QApplication.translate("PythonCheatSheet", "Important", None, QtGui.QApplication.UnicodeUTF8))
        self.decorators_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Decorators", None, QtGui.QApplication.UnicodeUTF8))
        self.examples_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Examples", None, QtGui.QApplication.UnicodeUTF8))
        self.yield_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Yield", None, QtGui.QApplication.UnicodeUTF8))
        self.exceptions_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Exceptions", None, QtGui.QApplication.UnicodeUTF8))
        self.twisted_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Twisted", None, QtGui.QApplication.UnicodeUTF8))
        self.search_label.setText(QtGui.QApplication.translate("PythonCheatSheet", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_button.setText(QtGui.QApplication.translate("PythonCheatSheet", "Clear", None, QtGui.QApplication.UnicodeUTF8))

